name: Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-checks:
    name: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        os:
          - "ubuntu-latest"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0

      - name: Lint Python
        run: |
          uv run -- ruff check

      - name: Check Python formatting
        run: |
          uv run -- ruff format --check

      - name: Check packaging
        run: |
          uv lock --check
