name: Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-checks:
    name: ${{ matrix.os }}
    timeout-minutes: 5

    strategy:
      matrix:
        os:
          - "ubuntu-latest"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

      - name: Lint Python
        run: |
          uv run -- ruff check

      - name: Check Python formatting
        run: |
          uv run -- ruff format --check

      - name: Check packaging
        run: |
          uv lock --check
