name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+[ab][0-9]+"

permissions: {}

jobs:
  release:
    name: Release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # For PyPI's trusted publishing.
      id-token: write

    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          enable-cache: false

      - name: Publish package
        run: |
          uv version "${GITHUB_REF#refs/*/}"
          uv build
          uv publish
